language: ruby
cache: bundler
rvm:
  - 2.1.5

env:
#  - DB=sqlite
#  - DB=mysql
  - DB=postgresql

before_script:
  - psql -c 'create database stokd_test' -U postgres

script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test:all
