# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c66c2117774cb18588ec6f55749bc52cdca22e7ca3fdb8eb3ce2136295c879fdb29c84387e3526e47950bb3a73bdbd0928f14347c3107949bb30d9d636420b4

test:
  secret_key_base: 68626c37283f6d2a97774e1f0d873d2736c6d0455d6e934220b49bc760de22daaa2d1e164bec44adbe2e62554fd27790ede0713d70fff5f62983c6bc39c9c4ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
